name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Print versions
        run: node --version && yarn --version

      - name: Run 'yarn install' and 'yarn test:prod'
        run: yarn install && yarn test:prod

      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.TEST_TOKEN }}
